language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5
install:
  - pip install -r requirements/base.txt -r requirements/tests.txt coveralls flake8 --use-mirrors
branches:
  only:
    - master
script: coverage run setup.py test
after_success:
  - coveralls
  - flake8 . --exclude=./okupy/tests/settings.py,./okupy/settings,setup.py
notifications:
  email:
    recipients:
      - okupy@gentoo.org
