language: python
python:
 - "2.7"
 - "3.3"
env:
 - DJANGO_VERSION=1.5
install:
 - pip install -r requirements.txt --use-mirrors
branches:
 only:
  - master
script: python manage.py test --settings=okupy.tests.settings tests
