language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
branches:
  only:
    - master
script: coverage run manage.py test --settings=okupy.tests.settings tests
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - okupy@gentoo.org
